### ISSUE TITLE
Cannot load the Sentiment Analysis widget

### ISSUE THREAD

**Issue by davidematera** [biolab/orange3-text#956] opened 2023-03-17 14:07 UTC
**Describe the bug**
Cannot load the Sentiment Analysis widget
when I drop the widget into my data-workflow it appears with the red error icon on the top

**To Reproduce**
1. Go to 'left panel - widget section for text analysis - from Orange3-text package'
2. Drag 'the Icon of Sentiment Analysis'
3. Drop it to 'the Data Workflow section'
4. Click into the 'Icon'
5. See error

**Expected behavior**
get into the standard view of the widget

**Orange version:**
Orange - About - version number.
3.32.0

**Text add-on version:**
Options - Add-ons - version number.
1.10.0

**Screenshots**
![image](https://user-images.githubusercontent.com/128158128/225926810-06d0e3f2-aedc-49fd-8c52-0438e3e9b7de.png)

**Operating system:**
Windows 10 on an dedicated VDI
Windows 10 Enterprise N
Version 21H2
Windows Feature Experience Pack 120.2212.4170.0

**Additional context**
VDI provided with limited network access

**Comment by PrimozGodec** [comment] 2023-07-28 10:37
Thank you for reporting the issue. I cannot reproduce this issue anymore. Maybe it is because we made changes to how models are downloaded as a part of https://github.com/biolab/orange3-text/pull/954. The failed line no longer exists, and languages are loaded differently. 

 I will close the issue but feel free to reopen it if the issue persists.

**Closed by PrimozGodec** 2023-07-28 10:37 UTC
Labels: friday
