### ISSUE TITLE
Orange text mining doesn't load any txt, docx data

### ISSUE THREAD

**Issue by ESTRELLAXXSTAR** [biolab/orange3-text#960] opened 2023-03-28 08:57 UTC
##### Text version

Hi,  I have successfully installed the text add on and gone through the tutorials. But still impossible to load my txt or docx data. The Import documents widget does not recognize it. After "reload" it indicates "0 documents, 1 skipped".  Is there any other add on I need?  Looking forward to hear from you.

**Comment by PrimozGodec** [comment] 2023-04-03 07:18
Thank you for submitting the issue. I tried it today, and it works for me. Can you provide the document not loaded for you so we can check what is going wrong?

**Comment by PrimozGodec** [comment] 2023-07-28 06:20
Closing since we cannot reproduce. Please reopen with an example of a document that is not read successfully.

**Closed by PrimozGodec** 2023-07-28 06:20 UTC
