### ISSUE TITLE
Tweet Profiler Stop Working

### ISSUE THREAD

**Issue by riksri1** [biolab/orange3-text#292] opened 2017-07-27 14:16 UTC
##### Orange version

0.2.3<0.2.4

##### Expected behavior
Tweet Profiler to give the analysis of Tweet Handle.

##### Actual behavior
System stops working

##### Additional info (worksheets, data, screenshots, ...)

![tweet profiler](https://user-images.githubusercontent.com/1832806/28675013-a0317ef2-72f7-11e7-9cea-d1374d90cb7a.png)
![orange text version](https://user-images.githubusercontent.com/1832806/28675021-a497456c-72f7-11e7-8f17-68696e58ee35.png)

**Comment by nikicc** [comment] 2017-07-27 14:28
@riksri1 sorry about this. We made some modifications to the server code and it looks like we broke something.

I made some corrections on the server side and now it works for me again on the `0.2.4` version. Can you please check, if the issue is also resolved for you? If it is, please close this issue.

**Comment by riksri1** [comment] 2017-07-27 17:19
Yes its working now thanks a ton

**Closed** 2017-07-27 17:19 UTC
