### ISSUE TITLE
Topic modelling instantly causes orange to freeze

### ISSUE THREAD

**Issue by gohchengyong** [biolab/orange3-text#847] opened 2022-05-09 11:15 UTC
Topic modelling instantly causes orange to freeze

I expect topic modelling to not freeze orange and crash my computer

Orange version 3.32.0

Text version 1.7.0

Windows 10 Home
![image](https://user-images.githubusercontent.com/105211189/167398681-d09c6c34-27b6-4c75-8c3c-23ae367a62f1.png)
![image](https://user-images.githubusercontent.com/105211189/167398840-9e2b7fd1-d262-4f19-a80c-68ffd48d85ed.png)
![image](https://user-images.githubusercontent.com/105211189/167398878-a18e62e2-db33-4bc3-bfc8-470993b5296b.png)

**Comment by ajdapretnar** [comment] 2022-05-09 11:25
I think a duplicate of #820.

**Closed by ajdapretnar** 2022-05-09 11:25 UTC

**Comment by gohchengyong** [comment] 2022-05-09 11:28
what now? no solution available? The topic modelling did run to 100%, but it just crashes aftwards.

**Comment by ajdapretnar** [comment] 2022-05-09 11:30
We were not able to debug this yet. All the progress will be recorded in #820, which also contains a summary of your reports.

**Comment by gohchengyong** [comment] 2022-05-09 11:31
okay thanks!
