### ISSUE TITLE
Wrong information about the number of tokens and types

### ISSUE THREAD

**Issue by kristinapdm** [biolab/orange3-text#920] opened 2022-11-11 18:52 UTC
**What's wrong? – Part 1 –SR**

The information about the number of tokens and types is not displayed correctly in the Select Rows widget. While the number of tokens changes according to the subset of data, the number of types displayed remains the same for all subsets.

A similar problem happens in the Word Enrichement and Word Cloud widgets. Both explained below. However, it might be always just Select Row's fault, since when WC is linked directly to the data, the information is/seems to be displayed correctly. 

**How can we reproduce the problem?** 

Load data with Import documents (conllu+tsv used) --> attach Select rows --> Define a condition for a subset --> Open Select rows --> Click bottom line information --> Compare information on the number of Types and Tokens

NB: The same issue appears also if I load raw data (in xlsx format) with Corpus --> Preprocess Text (with default settings corrected for language of the data) --> Select Rows ...

![image](https://user-images.githubusercontent.com/62376878/201409179-3060eb6e-424b-4b5a-9dd6-3f7d2eb1087b.png)

**Environment**

- Operating system: Windows
- Orange version: 3.33.0

**What's wrong? – Part 2 – WE**
A similar issue appears in the Word Enrichement widget.

The workflow:

![Posnetek zaslona 2022-11-11 202330](https://user-images.githubusercontent.com/62376878/201421333-6765dedf-d935-48ad-99a9-316a6be1313c.png)

When I open the WE widget (filtering not selected), it says (in the upper left corner) 15322 words displayed. However, when I open the info on input data from the bottom line, I get 15340 variables in the Selected data. Furthermore, as before, the number of types for Selected data and Data is the same, despite being related to different number of tokens.

![Posnetek zaslona 2022-11-11 202650](https://user-images.githubusercontent.com/62376878/201421421-1e1a9a0e-ce45-4fe3-88d9-0a7bbebcc41c.png)

Given that -- if I understand correctly -- these variables are actually types/lemmas which were output from the BoW widget and that Word Enrichment widget lists lemmas (rather than words/tokens; SIDENOTE: if indeed true, I suggest renaming "Word displayed" to "Types displayed"), the two numbers should be the same. But they are not. If this is actually ok, please explain where did I go wrong in my interpretation.

**What's wrong? – Part 3 – WC**

A similar issue appears in the Word Cloud widget but only when Select Rows is added. If it's not an issue, then I'm confused about the interpretations of the displayed numbers.

The workflow:
![image](https://user-images.githubusercontent.com/62376878/201423335-5e60e5fa-b5ea-4e14-8b87-fd2658d8e66b.png)

Results of WC when directly linked to the data - seems ok:
Input types: 14687
Output: 14687 types (Corpus output); 14687 instances (Counts output)

Results of WC when Select Rows is added to the workflow - doesn't seem ok
Input types: 14687
Output: 14684 types (Corpus output); 10225 Instances (Counts type)

**Comment by PrimozGodec** [comment] 2022-11-14 10:32
I just transferred the issue to the text addon repository.

You are right. The problem is that number of tokens is extracted from the underlying dictionary structure, which gets copied when select rows happen. We must fix the issue either by filtering the dictionary on select rows or by counting a number of types differently.

**Closed** 2023-08-25 08:27 UTC
Labels: friday, snack
