### ISSUE TITLE
text processing module with slow internet conection

### ISSUE THREAD

**Issue by pavelbs** [biolab/orange3-text#519] opened 2020-04-29 12:25 UTC
[textprocessingerr.txt](https://github.com/biolab/orange3-text/files/4551540/textprocessingerr.txt)

Hi! I have slow internet connection, less than 400Kbit/s. And when I use text preprocessing module I have an error.
If I disconnect my internet connection (disable wifi), the text processing module works fine.
If I have have internet connection more than 3Mbit/s, everything works fine.

**Comment by ajdapretnar** [comment] 2020-05-04 07:36
Thanks for reporting this, we will have a look.

**Comment by PrimozGodec** [comment] 2020-05-04 13:41
Hi @pavelbs, I tried to reproduce your error. I used the Network Link Conditioner to simulated a bad connection (different speeds, package lost rates, delays). I couldn't reproduce the particular error. It seems that in your case the text which is retrieved from the server is somehow corrupted, even the response from the server is 200 (OK). We can try to catch this particular error anyway. I am just interested in whether this error happens every time you try to load the Preprocess Text widget?

Btw. we have another issue with the Preprocess text widget. If I limit connection to much it takes forever to load the widget. It seems that there is no reasonable timeout set. I will check this issue again when #506 is merged.

**Comment by pavelbs** [comment] 2020-05-04 14:08
This error occurs every time I try to load the Preprocess Text widget. I live in a small village. My nearest cell tower is 20 km from me. I have 3G amplifier from aliexpress + 3G wifi router and handmade 3G antenna.
 (Orange38) [pavelbs@pavelbs-pc-manjaro orange3]$ ping mail.ru
PING mail.ru (94.100.180.201) 56(84) bytes of data.
64 bytes from mail.ru (94.100.180.201): icmp_seq=1 ttl=47 time=118 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=2 ttl=47 time=199 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=3 ttl=47 time=158 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=4 ttl=47 time=190 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=5 ttl=47 time=148 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=6 ttl=47 time=158 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=7 ttl=47 time=149 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=8 ttl=47 time=315 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=9 ttl=47 time=167 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=10 ttl=47 time=136 ms
64 bytes from mail.ru (94.100.180.201): icmp_seq=11 ttl=47 time=155 ms

**Comment by pavelbs** [comment] 2020-05-07 05:49
done
[response.pkl.zip](https://github.com/biolab/orange3-text/files/4590920/response.pkl.zip)

**Comment by PrimozGodec** [comment] 2020-05-07 09:57
@pavelbs thank you. This reveals the reason behind the error. Can I just ask you for another test? I changed the script a bit can you run it and send me a response? I just want to know if our assumptions are correct.

[example1.py.zip](https://github.com/biolab/orange3-text/files/4592207/example1.py.zip)

**Comment by pavelbs** [comment] 2020-05-07 12:17
done
[response.pkl.zip](https://github.com/biolab/orange3-text/files/4592852/response.pkl.zip)

**Comment by PrimozGodec** [comment] 2020-05-07 12:47
@pavelbs thank you for your help. The issue was not a slow internet connection but the fact that we were reaching our server through HTTP instead of https and your internet provider replaced a 404 (not reachable) response with a fancy HTML page. Using HTTPS solves the issue.

**Comment by pavelbs** [comment] 2020-05-07 16:32
What should I do?

**Comment by PrimozGodec** [comment] 2020-05-07 16:48
Nothing needs to be done from your side. I prepared a pull request with the fix, someone, from the team will merge it soon #524.
When it will be merged and the add-on will be released you can use a preprocess widget normally. 
If you want to use this fix earlier you would need to clone this addon and install it manually.

**Closed** 2020-05-22 08:10 UTC
