### ISSUE TITLE
Orange is crashes on PC running LDA with Text Mining

### ISSUE THREAD

**Issue by jeffreydconlin** [biolab/orange3-text#841] opened 2022-04-29 23:34 UTC
**What's wrong?**

Orange keeps crashing with Topic Modeling within workflow. This is happening on a PC with Windows, even after reinstalling Orange. 

I don't have any screenshots and can't get one now because I cannot open Orange at this point. I can tell you that at the top left of the screen it says Orange (Not Responding) and then it proceeds to spin in circles, shows a "0%" under the Topic Modeling label and then crashes. 

**How can we reproduce the problem?** 

The issue occurred multiple times. Orange was reinstalled and the issue persisted. 

**What's your environment?**

- Operating system: Windows/PC
- Orange version: 3.32.0
- How you installed Orange: From https://orangedatamining.com/download/#macos

**Comment by jeffreydconlin** [comment] 2022-05-02 14:03
The same issue has affected another student with Windows/PC. They have tried reinstalling Orange without success. The first student reports that the 3.32.0 reinstall fails to launch Orange at all.

Any updates or suggestions?

**Comment by ajdapretnar** [comment] 2022-05-03 07:00
Are you running LDA or LSI? The workflow you attached shows LSI.
It indeed works fine on Mac. I can give it a go on Windows later today/tomorrow.
Would you mind opening the Orange Command Prompt on Windows, run `pip freeze` and post the output here. Perhaps its an issue of different versions of libraries.

**Comment by ajdapretnar** [comment] 2022-05-09 11:26
Duplicate of #820.

**Closed by ajdapretnar** 2022-05-09 11:26 UTC
Labels: bug report
