### ISSUE TITLE
Bag of Words: crash on binary

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#349] opened 2018-06-20 10:21 UTC
##### Text version

0.3.0

##### Orange version

3.13

##### Expected behavior
Bag of Words works normally.

##### Actual behavior
BoW crashes when selecting binary option.

##### Steps to reproduce the behavior
Windows 10.
Install Orange from official installer.
Install Text from Options - Add-ons. (when restarting Orange, I get 'Please insert disk into drive D' error from pythonw.exe 🤔 )
Corpus (grimm-tales-selected) - Preprocess Text (default) - Bag of Words (use Binary).
❗️ Error is also unreported in Sentry, despite click Report error.

##### Additional info (worksheets, data, screenshots, ...)
Exception:
TypeError: only length-1 arrays can be converted to Python scalars
Module:
orangecontrib.text.vectorization.bagofwords:49
Widget Name:
Bag of Words
Widget Module:
orangecontrib.text.widgets.owbagofwords:66
Widget Scheme:
C:\Users\sanjam\AppData\Local\Temp\ows-sdvfrx2k.ows.xml
Version:
3.13.0
Environment:
Python 3.6.5 on Windows 10 10.0.17134 AMD64
Installed Packages:
AnyQt==0.0.8, Bottleneck==1.2.1, CacheControl==0.12.4, CommonMark==0.7.5, Orange3-Educational==0.1.8, Orange3-ImageAnalytics==0.2.0, Orange3-Text==0.3.0, Orange3==3.13.0, Pillow==5.1.0, PyJWT==1.6.4, PySocks==1.6.8, asn1crypto==0.24.0, atomicwrites==1.1.5, attrs==18.1.0, beautifulsoup4==4.6.0, biopython==1.71, blinker==1.4, boto3==1.7.31, boto==2.48.0, botocore==1.10.31, brotlipy==0.7.0, bz2file==0.98, certifi==2018.1.18, cffi==1.11.5, chardet==3.0.4, colorama==0.3.9, cryptography==2.2.2, docutils==0.14, docx2txt==0.6, future==0.16.0, gensim==3.4.0, h2==2.6.2, hpack==3.0.0, hyperframe==3.2.0, hypertemp==0.8.0, idna==2.6, jmespath==0.9.3, joblib==0.11, keyring==9.0, keyrings.alt==3.0, lap==0.3.0, lockfile==0.12.2, lxml==4.2.1, mkl-fft==1.0.0, mkl-random==1.0.1, more-itertools==4.2.0, msgpack-python==0.5.6, msgpack==0.5.6, nltk==3.2.4, numpy==1.13.3, oauthlib==2.1.0, odfpy==1.3.6, olefile==0.45.1, pdfminer3k==1.3.1, pip==9.0.3, pluggy==0.6.0, ply==3.11, py==1.5.3, pyOpenSSL==17.5.0, pycparser==2.18, pyqtgraph==0.10.0, pytest==3.6.0, python-dateutil==2.7.3, pywin32==223, requests-oauthlib==0.8.0, requests==2.18.4, rfc3986==1.1.0, s3transfer==0.1.13, scikit-learn==0.19.1, scipy==0.19.1, serverfiles==0.2.1, setuptools-git==1.2, setuptools==39.0.1, simhash==1.7.1, six==1.11.0, smart-open==1.5.7, tweepy==3.5.0, typing==3.6.4, urllib3==1.22, validate-email==1.3, wheel==0.31.0, wikipedia==1.4.0, win-inet-pton==1.0.1, wincertstore==0.2, xlrd==1.1.0
Machine ID:
93383153299428
Stack Trace:
Traceback (most recent call last):
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\widgets\utils\owbasevectorizer.py", line 66, in on_change
    self.commit()
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\Orange\widgets\gui.py", line 2013, in unconditional_commit
    do_commit()
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\Orange\widgets\gui.py", line 2021, in do_commit
    commit()
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\widgets\utils\owbasevectorizer.py", line 54, in commit
    self.apply()
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\widgets\utils\owbasevectorizer.py", line 58, in apply
    new_corpus = self.method.transform(self.corpus)
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\vectorization\base.py", line 17, in transform
    return self._transform(corpus, source_dict)
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\vectorization\bagofwords.py", line 78, in _transform
    X = matutils.corpus2csc(model[temp_corpus], dtype=np.float, num_terms=len(dic)).T
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\gensim\matutils.py", line 151, in corpus2csc
    for docno, doc in enumerate(corpus):
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\gensim\interfaces.py", line 193, in __iter__
    yield self.obj[doc]
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\gensim\models\tfidfmodel.py", line 376, in __getitem__
    tf_array = self.wlocal(np.array(tf_array))
  File "C:\Project\FRI\Orange\OrangeNew\lib\site-packages\orangecontrib\text\vectorization\bagofwords.py", line 49, in <lambda>
    (BINARY, lambda tf: int(tf > 0)),
TypeError: only length-1 arrays can be converted to Python scalars

Local Variables:
OrderedDict([('tf',
              array([ 1,  7,  1,  1,  8,  2,  1,  7,  1,  1,  1,  2,  3,  4,  4,  9,  1,
        1,  2,  9,  3,  2,  4,  1,  1,  1,  2,  2,  6,  3,  1,  1,  3,  4,
        1,  1,  2,  1,  3,  1,  2,  2,  6,  2,  4,  6,  1,  2,  2,  1,  2,
        1,  1,  3,  2,  1,  2, 12,  3,  1,  1,  1,  3,  5,  1,  2,  1,  1,
        8,  2,  2,  4, 10,  2,  1,  1,  1,  1,  2,  2,  2,  6,  1,  1,  7,
        1, 12,  1,  2,  1,  1,  3,  7,  1,  1,  9,  1,  9,  3,  1,  1,  1,
        1,  1,  3,  3,  1,  1,  1,  1,  4,  1,  4,  3,  1,  4,  1,  2,  2,
        2,  2,  3,  5,  2,  2,  1,  3, 18,  1,  7,  4,  4,  1,  2,  1,  2,
        1,  1, 20,  2,  1,  1,  1,  3,  1,  2,  2,  1,  1,  1,  3,  3,  2,
       14,  4,  2,  2,  4,  5,  7,  3,  3,  3,  1,  1,  1,  1,  6,  1,  1,
        6,  1,  7, 13,  1,  3,  1,  1,  1,  1,  3, 16,  8,  1,  2,  4,  1,
        3,  1,  1,  1,  1,  7,  2,  2, 12,  1,  3,  1, 10,  2,  2,  2,  1,
        6,  3,  2,  1,  2,  5,  1,  1,  1,  3,  4,  2,  1,  8,  1,  2,  2,
        5,  2,  3,  6,  3,  2,  1,  3,  5,  1,  1,  2, 20,  2,  1,  1,  4,
        2,  1,  8,  4,  2,  1,  4,  7,  6,  1,  1,  4,  1,  8, 10,  2,  2,
        5,  4, 11,  1,  1,  2,  6, 10,  4,  4,  9,  2,  2,  1,  9,  9,  3,
        1,  2,  5,  2,  1,  2,  3,  2,  2,  3,  4,  3,  2,  1,  1,  2,  1,
        1,  1,  5,  1,  2,  6,  1,  4,  1,  1,  3,  8,  2,  1,  2,  2,  1,
        1,  1,  6,  1,  1,  9,  1,  5,  1,  3,  1,  1,  1,  2,  8,  4,  1,
        2,  2, 16,  1,  2,  5,  1,  2,  2,  2,  2,  2,  1,  3,  1,  1,  2,
        3,  2,  3,  1,  1,  1,  8,  1,  1,  2,  1,  3,  4,  4,  2,  1,  3,
        1,  1,  1,  1,  2,  4,  2,  2,  2,  1,  1,  4,  8,  1,  1,  3,  1,
        3,  1,  8,  2,  2,  2,  7,  1,  3,  2,  3, 11,  1,  2,  8,  5,  5,
        2,  1,  1,  1,  1,  5,  1,  2,  4,  4,  7,  1,  1,  3,  1,  1,  2,
        1,  2,  3,  2,  8,  1,  3,  1,  1,  1,  6,  5,  2,  1,  1,  1,  6,
        1,  6,  2,  1,  2,  6,  5,  1,  4,  5,  8,  2,  3,  2,  1,  1,  2,
        5,  1,  2,  2,  1,  1,  2,  1,  1,  1,  1,  1,  1,  3,  4,  2, 16,
        1]))])

**Comment by robertcv** [comment] 2018-07-12 11:33
This issue should be resolved by https://github.com/biolab/orange3-text/commit/1aa8ff2dc7264ce2812c7ead219803a0b6f8ba00. The problem is there was no new release since then.

**Closed** 2018-07-16 14:45 UTC
Labels: bug
