### ISSUE TITLE
"corpus to network" widget does not work any more. 

### ISSUE THREAD

**Issue by jdzucker** [biolab/orange3-text#608] opened 2020-12-11 18:18 UTC
Describe the bug
What's wrong?
In your "corpus to network" widget, the output Network is missing, only "Node data" is there.

What is your operating system?
MAc OS Catalina 10.15.7

To Reproduce
Create a widget Corpus, choose the Book-Excerpts.tab
link it to "Corpus to Network" and then to "corpus explorer"

Expected behavior
The output "Network" is missing from the note "Corpus to Network". There is only data

Orange version:
3.27.1

Text add-on version:
1.2.0

Screenshots
![image](https://user-images.githubusercontent.com/12623800/101939641-91869d00-3be5-11eb-972e-87692588ac69.png)

Operating system:
OSX

Additional context
This widgets fails to output a network on all types of input. I have a course next Wednesday :-( Thanks in advance
THANKS FOR THE GREAT WORK

**Comment by ajdapretnar** [comment] 2020-12-14 07:57
Duplicate of https://github.com/biolab/orange3-text/issues/600.

**Closed by ajdapretnar** 2020-12-14 07:57 UTC
