### ISSUE TITLE
Servers not responding

### ISSUE THREAD

**Issue by rnacheva** [biolab/orange3-text#697] opened 2021-07-24 08:49 UTC
Hello,

I would like to report about an issue with Twitter Profiler. I am attaching the screenshot of the error with the module. 

The module is not usable from 23/7/2021. I attached xlsx file to the Corpus module and after the data loading, the error is shown. 

![изображение](https://user-images.githubusercontent.com/9884281/126863070-f98601fb-00dd-4f25-b274-eafeab78cb5b.png)

**Comment by ajdapretnar** [comment] 2021-08-03 09:48
Duplicate of #694.

**Closed by ajdapretnar** 2021-08-03 09:48 UTC
